version: "3"
services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama:
